FROM node:12-alpine3.10
ENV LOG_LEVEL "info"

ARG APP=app
ARG HOME=/home/node

ENV NPM_CONFIG_PREFIX=$HOME/.npm-global
ENV PATH=$PATH:$HOME/.npm-global/bin

WORKDIR $HOME/$APP

COPY --chown=node:node . $HOME/$APP
RUN chmod +x $HOME/$APP/docker-entrypoint.sh
RUN apk --update add curl ca-certificates && \
    cd $HOME/$APP && npm install && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apk/*

USER node

EXPOSE 3000

CMD ["npm", "start"]